### ISSUE TITLE
The train loss is nan

### ISSUE THREAD

**Issue by bbba-afk** [LJOVO/TranSalNet#1]
I retrain fine-tune&train.ipynb with the same dataset and setup, but the train loss is very easy to be nan. Have you encountered this situation? Can you provide a more detailed experimental environment such as random seed and progress of dataset?

**Comment by LJOVO** [comment]
Hi,
I have not encountered this kind of problem before. 
Please refer to the following supplementary experimental environment: 
`CUDA 11`  
`cuDNN 8.0.4`
For the SALICON dataset, the stimuli and saliency maps were simply resized from 640x480 to 384x288, and the fixation maps (_binary_) were generated from the _coordinates after resizing_.
The models were trained without specifying a particular random seed for loading datasets.

**Comment by bbba-afk** [comment]
thank you for your reply, the problem appears in the processing of the label.
