### ISSUE TITLE
Loading Fixation Maps of Salicon dataset

### ISSUE THREAD

**Issue by mr17m** [LJOVO/TranSalNet#2]
Hello,
In your train script you used `MyDataset` function and one of the arguments of this function is `fixation_dir=r'datasets\val\val_fixation/` . My question is that from which source you downloaded fixation maps (bmp files that also are mentioned in the csv files)? This is because the format of the fixation maps that are provided in [this link](http://salicon.net/challenge-2017/) are mat files. Should we do preprocessing with one of your scripts?

**Comment by LJOVO** [comment]
Hi,

In the official SALICON dataset, fixation maps are provided in .mat format. In this work, we converted these _.mat files_ into _.bmp fixation maps_ for model training. The specific method is to mark the fixation points according to the coordinates given in the .mat files, using pixels with a gray level of 255 on an all-black background. Then we can obtain image-format binary fixation maps.

**Comment by fadhfaiz** [comment]
Hi,

The specific dict_keys you utilized from the .mat files during the conversion process, such as 'header', 'version', 'globals', 'image', 'resolution', or 'gaze'?

**Comment by LJOVO** [comment]
> Hi,
> 
> The specific dict_keys you utilized from the .mat files during the conversion process, such as 'header', 'version', 'globals', 'image', 'resolution', or 'gaze'?

Hi，

I think it should be _gaze_.
