### ISSUE TITLE
Error tensor size during the training

### ISSUE THREAD

**Issue by fadhfaiz** [LJOVO/TranSalNet#6]
Hi,

I'm encountering an error during training that says "The size of tensor a (300) must match the size of tensor b (108) at non-singleton dimension 1". Can you help me troubleshoot this error?

**Comment by LJOVO** [comment]
Hi, 
I think this error could be caused by an unexpected input size. You may resolve this error by resizing the input image to 384×288.

**Comment by fadhfaiz** [comment]
Hi,

What about the actual size of BMP files?
